services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    env_file:
      - .env

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    env_file:
      - .env

volumes:
  db-data: